Add docker image publication and run with compose
Refs: #24
Closes: #24

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -8,6 +8,10 @@ on:
     branches:
       - main
 
+env:
+  REGISTRY: ghcr.io
+  IMAGE_NAME: ${{ github.repository }}
+
 jobs:
   static-analysis:
     name: Static Analysis
@@ -99,3 +103,51 @@ jobs:
 
       - name: Run tests
         run: ./gradlew test -x ktlintCheck
+
+  quick-test:
+    name: Docker Compose Health Check
+    runs-on: ubuntu-latest
+    needs: test
+
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Enable BuildKit
+        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
+
+      - name: Build and start services
+        run: docker compose up --build -d
+
+      - name: Wait for health endpoint
+        run: |
+          for i in {1..40}; do
+            if curl -fs http://localhost:8080/actuator/health > /dev/null; then
+              exit 0
+            fi
+            sleep 3
+          done
+          echo "Health check failed: application did not become ready"
+          docker compose logs
+          exit 1
+
+      - name: Shutdown services
+        if: always()
+        run: docker compose down -v
+
+  publish:
+    #if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+    name: Publish Docker Image
+    runs-on: ubuntu-latest
+    needs: quick-test
+    steps:
+      - uses: actions/checkout@v3
+      - name: Log in
+        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+
+      - name: Build image
+        # if some time we need versioning, we can use tags here
+        # like :${{ github.sha }} or :${{ github.ref_name }}-${{ github.sha }}
+        run: docker build -t $REGISTRY/$IMAGE_NAME:latest .
+
+      - name: Push image
+        run: docker push $REGISTRY/$IMAGE_NAME:latest
